# Generated by Django 3.2.23 on 2024-01-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendCV', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='cores_id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position_id',
        ),
        migrations.DeleteModel(
            name='Core',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
