# Generated by Django 3.2.23 on 2024-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
