# Generated by Django 3.2.23 on 2024-01-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240108_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='name',
        ),
    ]
