# Generated by Django 3.2.23 on 2024-01-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_role_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
