# Generated by Django 3.2.23 on 2024-03-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_service_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image',
        ),
    ]
