# Generated by Django 3.2.23 on 2024-01-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_role_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
