# Generated by Django 3.2.23 on 2024-01-09 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.role'),
            preserve_default=False,
        ),
    ]
