# Generated by Django 3.2.23 on 2024-01-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[(0, 'BLUE'), (1, 'GREEN'), (2, 'RED'), (3, 'YELLOW'), (4, 'TEAL'), (5, 'VIOLET')], max_length=20),
        ),
    ]
