# Generated by Django 3.2.23 on 2024-03-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240322_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='img_url',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.promotion'),
        ),
    ]
