# Generated by Django 3.2.23 on 2024-02-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.IntegerField(choices=[(0, 'BLUE'), (1, 'GREEN'), (2, 'RED'), (3, 'YELLOW'), (4, 'TEAL'), (5, 'VIOLET')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.IntegerField(choices=[(0, 'DISPONIBLE'), (1, 'AGOTADO'), (2, 'DESCATALOGADO')]),
        ),
    ]
