# Generated by Django 3.2.23 on 2024-03-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240326_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='services'),
            preserve_default=False,
        ),
    ]
