# Generated by Django 3.2.23 on 2024-02-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240201_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='products_related',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
