# Generated by Django 3.2.23 on 2024-01-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240111_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_role',
            new_name='role',
        ),
    ]
