# Generated by Django 3.2.23 on 2024-01-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='documentType',
            field=models.CharField(choices=[(1, 'DNI'), (2, 'CEDULA'), (3, 'PASAPORTE'), (4, 'OTRO')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.IntegerField(verbose_name=[(1, 'DNI'), (2, 'CEDULA'), (3, 'PASAPORTE'), (4, 'OTRO')]),
        ),
    ]
