# Generated by Django 3.2.23 on 2024-02-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240201_1045'),
        ('api', '0008_auto_20240131_1021'),
    ]

    operations = [
    ]
