# Generated by Django 3.2.23 on 2024-01-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='documentType',
            field=models.CharField(choices=[(0, 'DNI'), (1, 'CEDULA'), (2, 'PASAPORTE'), (3, 'OTRO')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
    ]
