# Generated by Django 3.2.23 on 2024-02-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_category_products_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products_related',
            field=models.IntegerField(default=0),
        ),
    ]
