# Generated by Django 3.2.23 on 2024-03-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=0, upload_to='services'),
            preserve_default=False,
        ),
    ]
