# Generated by Django 3.2.23 on 2024-02-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_category_products_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products_related',
        ),
    ]
