# Generated by Django 3.2.23 on 2024-02-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_0007_auto_20240201_1045_0008_auto_20240131_1021'),
        ('api', '0011_remove_category_products_related'),
    ]

    operations = [
    ]
