# Generated by Django 3.2.23 on 2024-04-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_customer_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.IntegerField(verbose_name=[(0, 'MASCULINO'), (1, 'FEMENINO')]),
        ),
    ]
