# Generated by Django 3.2.23 on 2024-04-05 17:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_saledetailsservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='bitrthdate',
            new_name='birthdate',
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(upload_to='customers'),
        ),
        migrations.AlterField(
            model_name='saledetailsservice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='saledetailsservice',
            name='total_item_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
