# Generated by Django 3.2.23 on 2024-04-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20240412_0918'),
        ('api', '0016_auto_20240410_1300'),
    ]

    operations = [
    ]
