# Generated by Django 3.2.23 on 2024-04-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_0015_auto_20240412_0918_0016_auto_20240410_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetailsproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
