# Generated by Django 3.2.23 on 2024-04-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20240417_1208'),
        ('api', '0018_alter_saledetailsproduct_id'),
    ]

    operations = [
    ]
