# Generated by Django 3.2.23 on 2024-05-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20240424_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='saleStatus',
            field=models.CharField(choices=[(0, 'PENDIENTE'), (1, 'EN_PROCESO'), (2, 'COMPLETADO')], default=2, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='photos/default.jpeg', null=True, upload_to='customers'),
        ),
    ]
