# Generated by Django 3.2.23 on 2024-06-21 16:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20240508_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ruc', models.IntegerField()),
                ('person_contact', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saledetailsproduct',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='impuesto'),
        ),
        migrations.AlterField(
            model_name='saledetailsservice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('date_purchase', models.DateField()),
                ('number_bill', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estatus', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_payment', models.DateField()),
                ('date_limit', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelled_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estatus', models.CharField(max_length=50)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPurchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_purchase', models.DateField()),
                ('item', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.purchase')),
            ],
        ),
    ]
