# Generated by Django 3.2.23 on 2024-07-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_notification_status_alter_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='list_archives',
            field=models.TextField(default='[]'),
        ),
    ]
