# Generated by Django 5.0.6 on 2024-07-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_notification_list_archives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpurchase',
            name='purchase',
        ),
        migrations.AddField(
            model_name='purchase',
            name='detailpurchase',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.detailpurchase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
