from api.model.UserModel import User
from api.model.RoleModel import Role
from api.model.CustomerModel import Customer
from api.model.SaleModel import Sale
from api.model.ProductModel import Product
from api.model.CategoryModel import Category
from api.model.PromotionModel import Promotion
from api.model.ServiceModel import Service
from api.model.SaleDetailsServiceModel import SaleDetailsService
from api.model.SaleDetailsProductModel import SaleDetailsProduct
from api.model.ProviderModel import Provider