from api.view.RoleView import *
from api.view.UserView import *
from api.view.ClientView import *
from api.view.SaleView import *
from api.view.GroupPermissionsView import *
from api.view.PermissionView import *
from api.view.ProductView import *
from api.view.CategoryView import *
from api.view.PromotionView import *
from api.view.ServiceView import *
from api.view.SaleDetailsServiceView import *
from api.view.SaleDetailsProductView import *